import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { NavBar } from "../components/containers/Nav";
import styles from "../styles/Home.module.css";
import { Box } from "../components/common/Box";
import { theme } from "../styles/theme";
import userstories from "../public/icons/sprint2userStories.png";
const Home: NextPage = () => {
  const bruh = 0;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box row>
        <NavBar />

        <Box css={{ padding: "5em", minWidth: "2000px", minHeight: "1500px" ,textAlign:'center' }}>
          <h1 style={{ fontStyle: "italic" }}>Sprint 2 Delivery</h1>
          <h3>User Stories:</h3>
          <Image
            src={userstories}
            style={{ minWidth: "1000px", minHeight: "500px" }}
            layout="responsive"
            unoptimized={true}
            loading="eager"
            alt="userstories"
          />
          <br></br>
          <a
            href="https://survey-9.group6.appsemble.app/en/survey"
            target="_blank"
            rel="noreferrer"
          >
            <h3 style={{ color: `${theme.colors.voilet100}` }}>
              Appsemble Form
            </h3>
          </a>
        </Box>
      </Box>
    </div>
  );
};

export default Home;
