import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { NavBar } from "../components/containers/Nav";
import styles from "../styles/Home.module.css";
import { Box } from "../components/common/Box";
import { theme } from "../styles/theme";
import userstories from "../public/icons/sprint2userStories.png";
import dim from "../public/icons/dim-logo.png";
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box row>
        <NavBar />

        <Box
          css={{
            padding: "5em",
            width: "900px",
          }}
        >
          <Image src={dim} alt="dim" />
        </Box>
      </Box>
    </div>
  );
};

export default Home;
